wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.43.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721775053
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.11.9
      5: 0.17.4
      6: 4.43.0.dev0
      8:
      - 5
      13: linux-x86_64
layer count:
  desc: null
  value: 32
d_model:
  desc: null
  value: 256
train epochs:
  desc: null
  value: 30
model id:
  desc: null
  value: ETTh1_512_96
model:
  desc: null
  value: BackboneModel
LLM used:
  desc: null
  value: Mamba1
